backend_splunk_url="REPLACE_IT_WITH_SPLUNK_URL:8089"
frontend_splunk_url="REPLACE_IT_WITH_SPLUNK_URL:8089"

system_generic_errors_alert_create=1
system_aggregator_errors_alert_create=0

fe_system_generic_errors_alert_create=1
fe_system_aggregator_errors_alert_create=1