backend_splunk_url="localhost:8089"
frontend_splunk_url="localhost:8089"

system_generic_errors_alert_create=1
system_aggregator_errors_alert_create=0

fe_system_generic_errors_alert_create=1
fe_system_aggregator_errors_alert_create=1